const data=[{
    id:1,  
    prductName:"Rimmel London Lasting Finish 25 Hour Foundation SPF 20 - Golden Honey",
    price:330,
    weight:"30Ml",
    id:2,  
    prductName:"Rimmel London Lasting Finish 25 Hour Foundation SPF 20 - Golden Honey",
    price:3300,
    weight:"30Ml",
    id:3,  
    prductName:"Rimmel London Lasting Finish 25 Hour Foundation SPF 20 - Golden Honey",
    price:3230,
    weight:"30Ml",
    id:4,  
    prductName:"Rimmel London Lasting Finish 25 Hour Foundation SPF 20 - Golden Honey",
    price:3350,
    weight:"30Ml",
    id:5,  
    prductName:"Rimmel London Lasting Finish 25 Hour Foundation SPF 20 - Golden Honey",
    price:3130,
    weight:"30Ml",
    id:6,  
    prductName:"Rimmel London Lasting Finish 25 Hour Foundation SPF 20 - Golden Honey",
    price:1330,
    weight:"320Ml",

}]